[tool.poetry]
name = "tradeapis"
version = "2.0.1"
description = "Stock Market Data Utilities and API Wrappers for Tradier, Polygon"
authors = ["Matt Stancliff <matt@genges.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.7.4"
orjson = "^3.6.8"
pandas = "^1.2.4"
arrow = "^1.1.0"
lark = "^1.0.0"
prettyprinter = "^0.18.0"
cachetools = "^4.2.2"
pandas-market-calendars = "^3.4"
loguru = "^0.6.0"

# mutil = { git = "https://github.com/mattsta/mutil.git", tag="1.2.3" }
mutil = { path = "../../mutil/", develop = true }
python-dotenv = "^0.19.1"
beautifulsoup4 = "^4.11.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
